spring.application.name=projeto_barbearia_agendamento
# Configurações de Conexão com o MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/projeto_barbearia?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#
## Configurações de Conexão com o MySQL
#spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:projeto_barbearia}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
#spring.datasource.username=${DB_USER:root}
#spring.datasource.password=${DB_PASSWORD:root}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## Configurações do Hibernate / JPA
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.open-in-view=false


# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
